# Site settings
title: Back to School 
#email: chicarrida@gmail.com	
#description: > # this means to ignore newlines until "baseurl:"
 # One month coding in Bali in Hacker Paradise, I'm so excited!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://github.com/chicarrida/chicarrida.github.io/blob/master" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: chicarrida 

# Build settings
markdown: kramdown
theme: architect

collections:
  rlxposts:
          output: true
  randomposts:
         output: true
