# Site settings
title: coding and relaxing in Bali
#email: chicarrida@gmail.com	
#description: > # this means to ignore newlines until "baseurl:"
 # One month coding in Bali in Hacker Paradise, I'm so excited!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: chicarrida 

# Build settings
markdown: kramdown

collections:
 rlxposts:
        output: true


